project: 
  type: website
  output-dir: docs

website:
  title: "Nicole Luisi: Data Analysis Portfolio"
  navbar:
    left:
      - text: "About Me"
        href: ./aboutme.html
      - text: "Projects"
        menu:
          - text: "R Coding Exercise"
            href: ./coding_exercise.html
          - text: "Data Analysis Exercise"
            href: ./dataanalysis_exercise.html
          - text: "Visualization Exercise"
            href: ./visualization_exercise.html
          - text: "Tidy Tuesday Exercise"
            href: ./tidytuesday_exercise.html
      - text: "Flu Analysis"
        menu:
          - text: "Wrangling"
            href: ./fluanalysis/code/wrangling.html
          - text: "Exploration"
            href: ./fluanalysis/code/exploration.html
          - text: "Model Fitting"
            href: ./fluanalysis/code/fitting.html
    right:
      - icon: github 
        href: https://github.com/nicole-luisi/nicoleluisi-MADA-portfolio.git    

format:
  html:
    theme: yeti
    highlight: zenburn
    css: styles.css
    toc: FALSE


